files:
  ignore:
    - 'node_modules/**/*.*'
rules:
  indentation:
    - 2
    -
      size: 4
  bem-depth: 0
  border-zero: 2
  brace-style:
    - 2
    -
      allow-single-line: false
  class-name-format: 2
  clean-import-paths:
    - 2
    -
      leading-underscore: false
  empty-args: 1
  empty-line-between-blocks:
    - 2
    -
      allow-single-line-rulesets: false
  extends-before-declarations: 2
  extends-before-mixins: 0
  final-newline: 2
  force-attribute-nesting: 1
  force-element-nesting: 2
  force-pseudo-nesting: 2
  function-name-format: 2
  hex-length: 2
  hex-notation: 2
  id-name-format: 2
  leading-zero:
    - 2
    -
      include: true
  mixin-name-format: 2
  mixins-before-declarations: 2
  nesting-depth: 1
  no-color-keywords: 2
  no-color-literals: 1
  no-css-comments: 1
  no-debug: 2
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-extends: 0
  no-ids: 1
  no-important: 1
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-misspelled-properties: 2
  no-qualifying-elements: 0
  no-trailing-whitespace: 2
  no-trailing-zero: 2
  no-transition-all: 0
  no-url-protocols: 2
  no-vendor-prefixes: 2
  no-warn: 2
  one-declaration-per-line: 2
  placeholder-in-extend: 0
  placeholder-name-format: 2
  property-sort-order:
    - 1
    -
      order: 'smacss'
  property-units: 0
  quotes: 2
  shorthand-values: 2
  single-line-per-selector: 0
  space-after-bang: 2
  space-after-colon: 2
  space-after-comma: 2
  space-around-operator: 2
  space-before-bang: 2
  space-before-brace: 2
  space-before-colon: 2
  space-between-parens: 2
  trailing-semicolon: 2
  url-quotes: 2
  variable-for-property: 0
  variable-name-format: 2
  zero-unit: 2
